###### Define the Microservice application -- k8s deployment  #####
## define the workload
server:
## define the workload as the deployment
  
  deployed: "true"
  name: acx-mall
  version: v1
  image:
    repository: ""
    tag:  ""
    pullPolicy: IfNotPresent
    imagePullSecrets: ""
## label the node with "schedulelabel=schedulelabel", the workload will be be scheduled to the labeled k8s node
  schedulelabel:  acx-mall
## the number of the replication of the pod
  replica: "1"
  command: 
    exec: "/bin/sh"
  args:
   - "-c"
   - | 
    APP_NAME="acx-mall"
    WORK_DIR="/opt/acx/${APP_NAME}"
    JAVA_HOME="/opt/java/openjdk"
    JAVA_OPTS=" -Xms1g -Xmx2g -XX:MaxDirectMemorySize=512M -server  -XX:+HeapDumpOnOutOfMemoryError "
    cd ${WORK_DIR}/bin
    $JAVA_HOME/bin/java -jar  ${JAVA_OPTS}   -Dhttps.proxyHost="10.0.35.251" -Dhttps.proxyPort="3128" -Dspring.config.location=${WORK_DIR}/conf/bootstrap.yaml   ${WORK_DIR}/bin/${APP_NAME}.jar
  livenessProbe: ""
  readinessProbe: ""
  resources: ""
## define the environment variable
  env: ""
## define the extra
  extraContainerargs: ""
  volumeMounts: ""
  volumes: ""
