server:
  port: 31220
  servlet:
    # context-path: /acx/mall
    session:
      # session超时，默认 30 分钟，不能小于1分钟
      timeout: 481m
      # 浏览器 Cookie 中 SessionID 名称
      cookie:
        name: Token
        path: /
      tracking-modes: COOKIE
spring:
  application:
    name: mall
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
      accept_single_value_as_array: true
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER}:${NACOS_PORT}
        namespace: ${NACOS_NAMESPACE}
        service: acx-mall
        register-enabled: true
  session:
    # Session 存储方式
    store-type: redis
    # Session 存储到 Redis 键的前缀
    redis:
      namespace: security:acx
  security:
    # 认证类型
    auth-type: local
    auth-method: POST
    token-tracking-modes: header
    # 提供端接受访问的token列表
    internal-access-tokens: nq3018M7Iz1952vvQmbjo3LjMqWhkKpj
    ignore-urls:
      - /goods-category/common-list
      - /goods-type/category
      - /goods-type/enable
      - /shop/*/baseInfo

# feign配置
feign:
  httpclient:
    enabled: true

swagger:
  enabled: false
  path:

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  metrics:
    tags:
      application: ${spring.application.name}


# Log4j2 解决2.14.1版本之前JNDI注入的安全问题
log4j2:
  formatMsgNoLookups: True

# mapper文件位置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
oss:
  accessKeyId: ${OSS_ACCESS_KEY_ID}
  accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
  endpoint: ${OSS_ENDPOINT}
  allowedRole: 'common,retaileradmin'
  superRole: 'superadmin,operateadmin'
  cdnName: ${CDN_NAME}
  public-bucket:
    name: ${OSS_BUCKET_NAME}
    write:
      callbackUrl: ''
      prefix: 'temp/'
      signatureExpire: '3000'
      sizeLimit: '30048576000'
      acl: 'public-read'
    read:
      signatureExpire: '3000'
  applications:
    goods:
      write:
        sizeLimit: '5048576000'
        acl: 'default'
    product:
      write:
        sizeLimit: '10048576000'
        acl: 'public-read'
    shops:
      write:
        sizeLimit: '2048576000'
        acl: 'public-read'

goods:
  recommend:
    maxShop: 5
    maxPlat: 10

reviewer:
  resident: 21938639253
  shop: 21938639253
  goods: 11842245290,11390589014,21174423784,21938639253

message:
  sms:
    system-name: isc
    domain: ${DOMAIN}
    goods-audit-result: 您的商品@goodsName提交的@applyType申请@result，请登录平台@domain 查看详情。
    goods-forced-off-shelves: 您的商品@goodsName因违规被强制下架，请登录平台@domain 查看详情。
    apply-audit-content: 您的@applyType申请@applyResult，请登录平台@domain 查看详情。
    shop-forced-close: 您的店铺因违规被强制闭店，请登录平台@domain 查看详情。
    shop-open-fail: 用户@userName（@fullName）提交的店铺@shopName开通失败，请登录平台@domain查看处理。
    verifyCodeSmsContent: 验证码@verifyCode，如非本人操作请忽略此短信(5分钟内有效)。
# 外部服务配置
external:
  authority:
    service-name: acx-user
    path: /internal/authority
  user:
    service-name: acx-user
    path: /internal/user
  resource:
    service-name: acx-resource
  appcenter:
    service-name: acx-appcenter
    shop-path: /acx/appcenter/internal/mallshopapp
    platform-path: /acx/appcenter/internal/platform
    asset-path: /acx/appcenter/internal/asset
  market:
    service-name: acx-market
    goods-path: /internal/goods
    path: /internal/order/sap
    price-path: /internal/marketprice
  customerservice:
    service-name: acx-customerservice
    shop-path: /acx/customerservice
  message:
    service-name: message
# xxl-job配置
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://${XXL_JOB_SERVER0}:${XXL_JOB_PORT}/xxl-job-admin,http://${XXL_JOB_SERVER1}:${XXL_JOB_PORT}/xxl-job-admin
    executor:
      address: ''
      appname: ${NAMESPACE}-acx-mall-executor
      ip: ''
      port: 31221
      logpath: /opt/acx/acx-mall/logs
      logretentiondays: 30
ocr:
  endpoint: ocr-api.cn-hangzhou.aliyuncs.com