{
 "title": "ct_5gmc_mc集合指标监控大盘",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "database_name", "label": "数据库名称", "query": "ct_5gmc_mc" },
   {
    "name": "collection_name",
    "label": "集合名称",
    "query": "DeliveryTask, IncomingMessage, NP, short_url"
   },
   { "name": "interval", "query": "30m,1h,6h,12h,1d,7d,14d,30d" },
   {
    "name": "ct_5gmc_mc_mongodb_object_max_count",
    "query": "1000000"
   },
   {
    "name": "ct_5gmc_mc_mongodb_object_max_totalSize",
    "query": "15000000"
   }
  ]
 },
 "panels": [
  {
   "title": "预期指标$database_name/$collection_name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((mongodb_collstats_storageStats_storageSize{collection=\"${collection_name}\",database=\"${database_name}\", rs_state=\"1\"}+mongodb_collstats_storageStats_totalIndexSize{collection=\"${collection_name}\",database=\"${database_name}\", rs_state=\"1\"})/${ct_5gmc_mc_mongodb_object_max_totalSize})*100",
     "legendFormat": "存储空间"
    },
    {
     "expr": "(mongodb_collstats_storageStats_count{collection=\"${collection_name}\",database=\"${database_name}\", rs_state=\"1\"}/${ct_5gmc_mc_mongodb_object_max_count})*100",
     "legendFormat": "记录数"
    }
   ]
  },
  {
   "title": "Query操作次数:",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_collstats_storageStats_count{database=\"${database_name}\", collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "记录数"
    },
    {
     "expr": "mongodb_top_insert_count{database=\"${database_name}\", collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "插入"
    },
    {
     "expr": "mongodb_top_queries_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "查询"
    },
    {
     "expr": "mongodb_top_update_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "修改"
    },
    {
     "expr": "mongodb_top_remove_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "删除"
    },
    {
     "expr": "mongodb_top_getmore_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "查询更多"
    },
    {
     "expr": "mongodb_top_writeLock_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "写锁"
    },
    {
     "expr": "mongodb_top_readLock_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "读锁"
    }
   ]
  },
  {
   "title": "Query操作次数增量[$interval]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(mongodb_collstats_storageStats_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}[5m]))",
     "legendFormat": "记录数"
    },
    {
     "expr": "floor(increase(mongodb_top_insert_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}[5m]))",
     "legendFormat": "插入"
    },
    {
     "expr": "floor(increase(mongodb_top_queries_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}[5m]))",
     "legendFormat": "查询"
    },
    {
     "expr": "floor(increase(mongodb_top_update_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}[5m]))",
     "legendFormat": "修改"
    },
    {
     "expr": "floor(increase(mongodb_top_remove_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}[5m]))",
     "legendFormat": "删除"
    },
    {
     "expr": "floor(increase(mongodb_top_getmore_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}[5m]))",
     "legendFormat": "查询更多"
    },
    {
     "expr": "floor(increase(mongodb_top_writeLock_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}[5m]))",
     "legendFormat": "写锁"
    },
    {
     "expr": "floor(increase(mongodb_top_readLock_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}[5m]))",
     "legendFormat": "读锁"
    }
   ]
  },
  {
   "title": "Query操作时长(微秒)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_top_insert_time{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"} / mongodb_top_insert_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "插入"
    },
    {
     "expr": "mongodb_top_queries_time{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"} / mongodb_top_queries_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "查询"
    },
    {
     "expr": "mongodb_top_update_time{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}/mongodb_top_update_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "修改"
    },
    {
     "expr": "mongodb_top_remove_time{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}/mongodb_top_remove_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "删除"
    },
    {
     "expr": "mongodb_top_getmore_time{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"} / mongodb_top_getmore_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "查询更多"
    },
    {
     "expr": "mongodb_top_writeLock_time{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"} / mongodb_top_writeLock_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "写锁"
    },
    {
     "expr": "mongodb_top_readLock_time{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"} / mongodb_top_readLock_count{database=\"${database_name}\",collection=\"${collection_name}\",rs_state=\"1\"}",
     "legendFormat": "读锁"
    }
   ]
  },
  {
   "title": "存储空间",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_collstats_storageStats_count{database=\"${database_name}\", collection=\"${collection_name}\", rs_state=\"1\"}",
     "legendFormat": "记录数"
    },
    {
     "expr": "mongodb_collstats_storageStats_size{database=\"${database_name}\", collection=\"${collection_name}\", rs_state=\"1\"}",
     "legendFormat": "totalSize"
    },
    {
     "expr": "mongodb_collstats_storageStats_avgObjSize{database=\"${database_name}\", collection=\"${collection_name}\", rs_state=\"1\"}",
     "legendFormat": "avgObjSize"
    },
    {
     "expr": "mongodb_collstats_storageStats_size{database=\"${database_name}\", collection=\"${collection_name}\", rs_state=\"1\"}",
     "legendFormat": "size"
    },
    {
     "expr": "mongodb_collstats_storageStats_totalIndexSize{database=\"${database_name}\", collection=\"${collection_name}\", rs_state=\"1\"}",
     "legendFormat": "IndexTotalSize"
    }
   ]
  }
 ]
}