#////////////////////////////////////////////////////////////
#/
#/ File: configmap.yaml
#/
#////////////////////////////////////////////////////////////
#/
#/ Author: Xia Zeng Wu
#/
#/
#////////////////////////////////////////////////////////////

{{- $server := (empty .Values.server.name | ternary  .Release.Name .Values.server.name   )  }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $server }}-{{ .Values.server.version }}-conf-env
data:
{{ (.Files.Glob "files/conf/*").AsConfig | indent 2 }}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $server }}-{{ .Values.server.version }}-script-env
data:
{{ (.Files.Glob "files/script/*").AsConfig | indent 2 }}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $server }}-{{ .Values.server.version }}-data-env
data:
{{ (.Files.Glob "files/data/*").AsConfig | indent 2 }}


