#////////////////////////////////////////////////////////////
#/
#/ File: configmap.yaml
#/
#////////////////////////////////////////////////////////////
#/
#/ Author: Xia Zeng Wu
#/
#/ Copyright (c) 2018, 2024 All rights reserved.
#/
#////////////////////////////////////////////////////////////

{{- $server := (empty .Values.server.name | ternary  .Release.Name .Values.server.name   )  }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $server }}-{{ .Values.server.version }}-env
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}

---
