apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-role
  namespace: test-1
rules:
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - get 
    - list
    - watch
