apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-display
  namespace: event-example
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: hello-display
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: event-display
          image: 192.168.0.34:10001/library/knative-releases/knative.dev/eventing/cmd/event_display:v1.2.0

---

kind: Service
apiVersion: v1
metadata:
  name: hello-display
  namespace: event-example 
spec:
  selector:
    app: hello-display
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

