{
 "title": "Kafka Metrics",
 "description": "Dashboard for metrics jmx_exporter protmetheus",
 "tags": [
  "stable",
  "kafka",
  "数智云原生平台"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate_value, job)"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate_value{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
    }
   },
   {
    "name": "online_broker",
    "query": {
     "query": "query_result(count(up{job=~\"$job\"}))"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_brokers, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "broker 日常监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "request queue size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kafka_server_request_queue_size{instance=~\"$broker\"}"
      }
     ]
    },
    {
     "title": "brokerNetworkProcessorAvgIdlePercent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "kafka_network_processor_idlepercent_value{instance=~\"$broker\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "topic 日常监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message in per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"$topic\"}[5m])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Lag by  Consumer Group",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{instance=~\"$instance\",topic=~\"$topic\"}) by (consumergroup, topic)"
      }
     ]
    },
    {
     "title": "Message in per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~\"$instance\", topic=~\"$topic\"}[5m])/5) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message consume per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{instance=~\"$instance\",topic=~\"$topic\"}) by (consumergroup, topic)"
      }
     ]
    },
    {
     "title": "topic partition num ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "kafka_topic_partitions{topic=~\"$topic\"}"
      }
     ]
    },
    {
     "title": "topic partition replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "kafka_topic_partition_replicas{topic=~\"$topic\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Brokers Online",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kafka_server_replicamanager_total_leadercount_value{job=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Active Controllers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount_value{job=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Total of Topics",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount_value{job=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_total_underreplicatedpartitions_value{job=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Online Partitions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_total_partitioncount_value{job=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Offline Partitions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount_value{job=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Controller and Followers ",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "kafka_controller_kafkacontroller_activecontrollercount_value{job=~\"$job\"}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 9, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",topic=\"\"}[5m]))"
      }
     ]
    },
    {
     "title": "Partitions Leader and Replica Per Broker",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 15 },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_total_leadercount_value{job=~\"$job\"} / kafka_server_replicamanager_total_partitioncount_value{job=\"$job\"} * 100"
      },
      {
       "expr": "kafka_server_replicamanager_total_leadercount_value{job=~\"$job\"}"
      },
      {
       "expr": "count(kafka_server_replicamanager_total_partitioncount_value{job=~\"$job\"} <= 1)by(instance)"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 9, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",topic=\"\"}[$__range]))"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
     "repeat": "broker",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (kafka_network_socketserver_networkprocessoravgidlepercent{job=\"$job\",instance=~\"$broker\"}*100)"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "gauge",
     "description": "If <= 0 is very idle",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
     "repeat": "broker",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - kafka_server_kafkarequesthandlerpool_total_requesthandleravgidlepercent_oneminuterate{job=\"$job\",instance=~\"$broker\"} / 10000000"
      }
     ]
    },
    {
     "title": "Partitions Leader Per Broker",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "kafka_cluster_partition_replicascount{job=~\"$job\",topic=~\"$topic\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(request)"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(request)"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(request)"
      }
     ]
    },
    {
     "title": "Produce Latency 99th per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(instance)"
      }
     ]
    },
    {
     "title": "FetchConsumer Latency 99th per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(instance)"
      }
     ]
    },
    {
     "title": "FetchFollow Latency 99th per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Messages In Per Topic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "reqps", "label": "Message/s" }
     ],
     "targets": [
      {
       "expr": "sort(sum(kafka_server_brokertopicmetrics_messagesinpersec_oneminuterate{job=\"$job\",instance=~\"$broker\",topic!=\"\",topic=~\"$topic\"})by(topic))",
       "legendFormat": "Topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Bytes In Per Topic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_brokertopicmetrics_bytesinpersec_oneminuterate{job=\"$job\",topic!=\"\",instance=~\"$broker\",topic=~\"$topic\"})by(topic)",
       "legendFormat": "Topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Total Produce Request Rate Per Topic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_brokertopicmetrics_totalproducerequestspersec_oneminuterate{job=\"$job\",instance=~\"$broker\",topic!=\"\",topic=~\"$topic\"})by(topic)",
       "legendFormat": "Topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Bytes Out Per Topic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_brokertopicmetrics_bytesoutpersec_oneminuterate{job=\"$job\",instance=~\"$broker\",topic!=\"\",topic=~\"$topic\"})by(topic)",
       "legendFormat": "Topic: {{topic}}"
      }
     ]
    },
    {
     "title": "Produce Request Per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_network_requestmetrics_requestspersec_count{request=~\"Produce, version=8\",job=\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Request: {{instance}}"
      },
      {
       "expr": "sum(kafka_network_requestmetrics_requestspersec_count{request=~\"Produce, version=9\",job=\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Request: {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes In / Out Per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "Bps", "label": "In (-) / Out (+)" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_brokertopicmetrics_bytesoutpersec_oneminuterate{job=\"$job\",instance=~\"$broker\",topic!=\"\"})by(instance)",
       "legendFormat": "Bytes Out [{{instance}}]"
      },
      {
       "expr": "sum (kafka_server_brokertopicmetrics_bytesinpersec_oneminuterate{job=\"$job\",instance=~\"$broker\",topic!=\"\"})by(instance)",
       "legendFormat": "Bytes In [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Failed Produce Request Per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_total_failedproducerequestspersec_oneminuterate{job=~\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Produce Request Per Topic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_total_failedproducerequestspersec_oneminuterate{job=~\"$job\",topic!=\"\",instance=~\"$broker\",topic=~\"$topic\"})by(topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Failed Fetch Request Per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_total_failedfetchrequestspersec_oneminuterate{job=~\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Fetch Request Per Topic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_total_failedfetchrequestspersec_oneminuterate{job=~\"$job\",topic!=\"\",instance=~\"$broker\",topic=~\"$topic\"})by(topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Disconnects Per Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ms", "label": "Time/ms" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_sessionexpirelistener_total_zookeeperdisconnectspersec_oneminuterate{job=\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Expires Per Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "ms", "label": "Time/ms" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_sessionexpirelistener_total_zookeeperexpirespersec_oneminuterate{job=\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Request Latency Ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "ms", "label": "Time/ms" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_zookeeperclientmetrics_total_zookeeperrequestlatencyms_count{job=\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "Isr Shrinks / Isr Expands Per Sec",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops", "label": "Expands (-) / Shrinks (+)" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_replicamanager_total_isrshrinkspersec_oneminuterate{job=\"$job\",instance=~\"$broker\"})",
       "legendFormat": "ISR Shrinks Per Sec"
      },
      {
       "expr": "sum (kafka_server_replicamanager_total_isrexpandspersec_oneminuterate{job=\"$job\",instance=~\"$broker\"})",
       "legendFormat": "ISR Expands Per Sec"
      }
     ]
    },
    {
     "title": "FetchFollower Request Per Broker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"FetchFollower\",job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
       "legendFormat": "Request: {{instance}}"
      }
     ]
    },
    {
     "title": "Total Fetch Request Per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "reqps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_brokertopicmetrics_total_totalfetchrequestspersec_oneminuterate{job=\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "Leader Election Rate Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (irate(kafka_controller_controllerstats_leaderelectionrateandtimems_count{job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Requests Waiting in the Producer Purgatory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize_produce_value{job=\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Broker {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Requests Waiting in the Fetch Purgatory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize_fetch_value{job=\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Broker {{instance}}"
      }
     ]
    },
    {
     "title": "FetchConsumer Request Per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_network_requestmetrics_requestspersec_count{job=\"$job\",instance=~\"$broker\",request=\"FetchConsumer, version=11\"})+sum(kafka_network_requestmetrics_requestspersec_count{job=\"$job\",instance=~\"$broker\",request=\"FetchConsumer, version=12\"})",
       "legendFormat": "Request: {{instance}}"
      }
     ]
    },
    {
     "title": "Log Flush Stats Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (irate(kafka_log_logflushstats_logflushrateandtimems_count{job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Usage Segment Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort(sum(kafka_log_log_size{job=~\"$job\",instance=~\"$broker\"})by(instance))",
       "legendFormat": "Instance Broker:  {{instance}}"
      }
     ]
    },
    {
     "title": "Count Partition per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sort(sum(kafka_server_replicamanager_total_partitioncount_value{job=~\"$job\"}) by (instance))",
       "legendFormat": "Instance Broker:  {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent", "label": "Usage/s" }
     ],
     "targets": [
      {
       "expr": "java_lang_operatingsystem_systemcpuload{job=~\"$job\",instance=~\"$broker\"}* 100"
      },
      {
       "expr": "java_lang_operatingsystem_processcpuload{job=~\"$job\",instance=~\"$broker\"}* 100"
      }
     ]
    },
    {
     "title": "JVM Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(java_lang_memory_heapmemoryusage_used{job=\"$job\",instance=~\"$broker\"} )"
      }
     ]
    },
    {
     "title": "JVM Threads Current",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "java_lang_threading_threadcount{job=\"$job\",instance=~\"$broker\"}"
      },
      {
       "expr": "java_lang_threading_daemonthreadcount{job=\"$job\",instance=~\"$broker\"}"
      },
      {
       "expr": "java_lang_threading_peakthreadcount{job=\"$job\",instance=~\"$broker\"}"
      },
      {
       "expr": "java_lang_threading_totalstartedthreadcount{job=\"$job\",instance=~\"$broker\"}"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$broker\"}[1m]))"
      }
     ]
    }
   ]
  }
 ]
}