apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: redis-client
spec:
  template:
    metadata:
      name: redis-client-v1
      annotations:
        autoscaling.knative.dev/min-scale: "2"
    spec:
      containers:
        - name: redis-client
          image: im31.cn:10001/library/redis-client:v2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          command:
            - "/bin/sh"
            - "-c"
            - |
              java -jar -server \
              -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent \
              -Djava.awt.headless=true \
              /app.jar \
              --spring.profiles.active=test \
  traffic:
    - tag: v1
      revisionName: redis-client-v1
      percent: 100