apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: whalesay          # invoke the whalesay template
  arguments:
    parameters:
      - name : message
        value: hello world jackey xia!
  templates:
    - name: whalesay              # name of the template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "{{inputs.parameters.message}}" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m

