{
 "title": "本地存储 pvc 使用率 Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "kafka pvc 使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "data-kafka-0 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"data-kafka-0\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"data-kafka-0\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "data-kafka-1 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"data-kafka-1\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"data-kafka-1\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "data-kafka-2 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"data-kafka-2\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"data-kafka-2\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "data-kafka-zookeeper-0 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"data-kafka-zookeeper-0\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"data-kafka-zookeeper-0\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "data-kafka-zookeeper-1 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"data-kafka-zookeeper-1\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"data-kafka-zookeeper-1\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "data-kafka-zookeeper-2 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"data-kafka-zookeeper-2\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"data-kafka-zookeeper-2\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  { "title": "mongodb pvc 使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "datadir-mongodb-mongodb-sharded-shard0-data-0 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-shard0-data-0\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-shard0-data-0\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "datadir-mongodb-mongodb-sharded-shard0-data-1 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-shard0-data-1\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-shard0-data-1\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "datadir-mongodb-mongodb-sharded-shard0-data-2 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-shard0-data-2\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-shard0-data-2\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "datadir-mongodb-mongodb-sharded-configsvr-0 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-configsvr-0\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-configsvr-0\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "datadir-mongodb-mongodb-sharded-configsvr-1 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-configsvr-1\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-configsvr-1\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "datadir-mongodb-mongodb-sharded-configsvr-2 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-configsvr-2\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"datadir-mongodb-mongodb-sharded-configsvr-2\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "redis pvc 使用率",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "redis-data-redis-redis-cluster-0 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-0\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-0\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "redis-data-redis-redis-cluster-1 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-1\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-1\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "redis-data-redis-redis-cluster-2 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-2\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-2\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "redis-data-redis-redis-cluster-3 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-3\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-3\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "redis-data-redis-redis-cluster-4 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-4\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-4\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "redis-data-redis-redis-cluster-5 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-5\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"redis-data-redis-redis-cluster-5\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  { "title": "seaweedfs pvc 使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "data-seaweedfs-volume-0 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"data-seaweedfs-volume-0\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"data-seaweedfs-volume-0\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "data-seaweedfs-volume-1 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"data-seaweedfs-volume-1\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"data-seaweedfs-volume-1\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "data-seaweedfs-volume-2 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"data-seaweedfs-volume-2\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"data-seaweedfs-volume-2\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "idx-seaweedfs-volume-0 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"idx-seaweedfs-volume-0\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"idx-seaweedfs-volume-0\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "idx-seaweedfs-volume-1 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"idx-seaweedfs-volume-1\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"idx-seaweedfs-volume-1\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  },
  {
   "title": "idx-seaweedfs-volume-2 使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"idx-seaweedfs-volume-2\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"idx-seaweedfs-volume-2\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}} pvc使用率"
    }
   ]
  }
 ]
}